### ISSUE TITLE
"Look down during exaggerated flight" Camera example has bad behavior in Columbus View

### ISSUE THREAD

**Issue by robdan7** [robdan7/cesium#7]
pitch: -Cesium.Math.PI_OVER_TWO gör att kameran funkar.

**Comment by robdan7** [comment]
Log: maximumHeight gör att det slutar funkar någonstans mellan 7005000 och 8000000.

**Comment by robdan7** [comment]
Notera rad 3644 i Scene.js

**Comment by OskarHavo** [comment]
Liknande problem
https://github.com/CesiumGS/cesium/issues/3674
https://github.com/CesiumGS/cesium/pull/5070
